name: 每日下载更新

on:
  schedule:
    # 每天北京时间上午9点执行 (UTC+8)
    - cron: '0 1 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  download-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: 设置Git配置
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: 下载压缩文件
      run: |
        echo "开始下载压缩文件..."
        curl -L -o "单线路.zip" "https://gitee.com/PizazzXS/another-d/raw/master/%E5%8D%95%E7%BA%BF%E8%B7%AF.zip"
        echo "下载完成"
    
    - name: 检查文件是否下载成功
      run: |
        if [ ! -f "单线路.zip" ]; then
          echo "下载失败，文件不存在"
          exit 1
        fi
        echo "文件下载成功，大小: $(ls -lh 单线路.zip | awk '{print $5}')"
    
    - name: 清理旧文件
      run: |
        echo "清理旧文件..."
        # 删除之前解压的内容（除了.git目录和当前下载的zip文件）
        find . -maxdepth 1 -type d ! -name ".git" ! -name "." -exec rm -rf {} + || true
        echo "旧文件清理完成"
    
    - name: 解压文件
      run: |
        echo "开始解压文件..."
        # 检查文件是否存在
        if [ ! -f "单线路.zip" ]; then
          echo "错误：找不到单线路.zip文件"
          exit 1
        fi
        unzip -o "单线路.zip" -d .
        echo "解压完成"
        
        # 显示解压后的文件结构
        echo "解压后的文件结构:"
        ls -la
    
    - name: 清理压缩文件
      run: |
        rm -f "单线路.zip"
        echo "压缩文件已清理"
    
    - name: 检查是否有更改
      id: check-changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "检测到文件更改"
          echo "has-changes=true" >> $GITHUB_OUTPUT
        else
          echo "没有检测到文件更改"
          echo "has-changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: 提交更改
      if: steps.check-changes.outputs.has-changes == 'true'
      run: |
        echo "提交更改到仓库..."
        git add .
        git commit -m "自动更新: $(date '+%Y-%m-%d %H:%M:%S')"
        git push origin main
        echo "更改已提交并推送"
    
    - name: 无更改通知
      if: steps.check-changes.outputs.has-changes == 'false'
      run: |
        echo "没有检测到文件更改，跳过提交"
