name: 每日下载更新

on:
  schedule:
    # 每天北京时间上午9点执行 (UTC+8)
    - cron: '0 1 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  download-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: 设置Git配置
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: 下载压缩文件
      run: |
        echo "开始下载压缩文件..."
        curl -L -o "download.zip" "https://gitee.com/PizazzXS/another-d/raw/master/%E5%8D%95%E7%BA%BF%E8%B7%AF.zip"
        echo "下载完成"
        
        # 显示下载后的文件信息
        echo "下载后的文件列表:"
        ls -la *.zip || echo "没有找到zip文件"
        
        # 检查文件是否存在
        if [ -f "download.zip" ]; then
          echo "文件下载成功，大小: $(ls -lh download.zip | awk '{print $5}')"
        else
          echo "下载失败，文件不存在"
          exit 1
        fi
    
    - name: 验证下载文件
      run: |
        echo "验证下载的文件..."
        
        # 显示当前目录内容
        echo "当前目录文件列表:"
        ls -la
        
        # 检查zip文件是否存在
        if [ ! -f "download.zip" ]; then
          echo "错误：找不到download.zip文件"
          echo "尝试查找所有zip文件:"
          find . -name "*.zip" -type f
          exit 1
        fi
        
        # 检查文件大小
        echo "文件大小: $(ls -lh download.zip | awk '{print $5}')"
        
        # 检查文件类型
        echo "文件类型: $(file download.zip)"
        
        # 尝试列出zip文件内容
        echo "zip文件内容:"
        unzip -l download.zip || echo "无法列出zip文件内容"
    
    - name: 解压文件
      run: |
        echo "开始解压文件..."
        
        # 检查zip文件是否存在
        if [ ! -f "download.zip" ]; then
          echo "错误：找不到download.zip文件"
          exit 1
        fi
        
        # 解压文件
        unzip -o "download.zip" -d .
        echo "解压完成"
        
        # 显示解压后的文件结构
        echo "解压后的文件结构:"
        ls -la
        
        # 清理zip文件
        rm -f "download.zip"
        echo "压缩文件已清理"
    
    - name: 清理旧文件
      run: |
        echo "清理旧文件..."
        
        # 显示清理前的文件结构
        echo "清理前的文件结构:"
        ls -la
        
        # 删除之前解压的内容（除了.git目录）
        find . -maxdepth 1 -type d ! -name ".git" ! -name "." -exec rm -rf {} + || true
        
        # 显示清理后的文件结构
        echo "清理后的文件结构:"
        ls -la
    
    - name: 检查是否有更改
      id: check-changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "检测到文件更改"
          echo "has-changes=true" >> $GITHUB_OUTPUT
        else
          echo "没有检测到文件更改"
          echo "has-changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: 提交更改
      if: steps.check-changes.outputs.has-changes == 'true'
      run: |
        echo "提交更改到仓库..."
        git add .
        git commit -m "自动更新: $(date '+%Y-%m-%d %H:%M:%S')"
        git push origin main
        echo "更改已提交并推送"
    
    - name: 无更改通知
      if: steps.check-changes.outputs.has-changes == 'false'
      run: |
        echo "没有检测到文件更改，跳过提交"
