name: 同步文件

on:
  schedule:
    # 每天北京时间上午9点执行 (UTC+8)
    - cron: '0 1 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        persist-credentials: true
    
    - name: 设置Git配置
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: 下载并解压文件
      run: |
        echo "开始下载文件..."
        
        # 下载文件
        curl -L -o "data.zip" "https://gitee.com/PizazzXS/another-d/raw/master/%E5%8D%95%E7%BA%BF%E8%B7%AF.zip"
        
        # 检查下载是否成功
        if [ ! -f "data.zip" ]; then
          echo "下载失败"
          exit 1
        fi
        
        echo "下载成功，文件大小: $(ls -lh data.zip | awk '{print $5}')"
        
        # 显示当前目录
        echo "当前目录内容:"
        ls -la
        
        # 解压文件
        echo "开始解压..."
        unzip -o "data.zip" -d .
        echo "解压完成"
        
        # 显示解压后的内容
        echo "解压后的内容:"
        ls -la
        
        # 修复api.json中的相对路径
        echo "修复api.json中的相对路径..."
        if [ -f "TVBoxOSC/tvbox/api.json" ]; then
          # 获取仓库信息
          REPO_OWNER="leiyou-li"
          REPO_NAME="xiaosaautomatic"
          BRANCH="main"
          BASE_URL="https://raw.githubusercontent.com/$REPO_OWNER/$REPO_NAME/refs/heads/$BRANCH/TVBoxOSC/tvbox"
          
          echo "仓库URL: $BASE_URL"
          
          # spider.jar保持相对路径不变，只修改其他目录路径
          
          # 替换./json/为完整URL
          sed -i "s|\\./json/|$BASE_URL/json/|g" "TVBoxOSC/tvbox/api.json"
          
          # 替换./js/为Gitee URL格式
          JS_GITEE_URL="https://gitee.com/zxmoyun/test/raw/master/mjs/"
          sed -i "s|\\./js/|$JS_GITEE_URL|g" "TVBoxOSC/tvbox/api.json"
          
          # 修复js目录URL格式，使用Gitee URL
          sed -i "s|https://raw.githubusercontent.com/$REPO_OWNER/$REPO_NAME/refs/heads/$BRANCH/TVBoxOSC/tvbox/js/|$JS_GITEE_URL|g" "TVBoxOSC/tvbox/api.json"
          sed -i "s|https://raw.githubusercontent.com/$REPO_OWNER/$REPO_NAME/main/TVBoxOSC/tvbox/js/|$JS_GITEE_URL|g" "TVBoxOSC/tvbox/api.json"
          
          # 替换./py/为完整URL
          sed -i "s|\\./py/|$BASE_URL/py/|g" "TVBoxOSC/tvbox/api.json"
          
          # 替换./XBPQ/为完整URL
          sed -i "s|\\./XBPQ/|$BASE_URL/XBPQ/|g" "TVBoxOSC/tvbox/api.json"
          
          # 替换./XYQHiker/为完整URL
          sed -i "s|\\./XYQHiker/|$BASE_URL/XYQHiker/|g" "TVBoxOSC/tvbox/api.json"
          
          echo "api.json路径修复完成"
          echo "已将相对路径替换为GitHub仓库URL"
        else
          echo "未找到api.json文件，跳过路径修复"
        fi
        
        # 删除zip文件
        rm -f "data.zip"
        echo "清理完成"
    
    - name: 检查更改
      id: check-changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "检测到文件更改"
          echo "has-changes=true" >> $GITHUB_OUTPUT
        else
          echo "没有检测到文件更改"
          echo "has-changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: 提交更改
      if: steps.check-changes.outputs.has-changes == 'true'
      run: |
        echo "提交更改..."
        git add .
        git commit -m "自动更新: $(date '+%Y-%m-%d %H:%M:%S')"
        git push origin HEAD:main
        echo "更改已提交"
